### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by grim3212** [grim3212/grim-pack#70]
Current set of tasks I would like to get completed other than those people have told me.

- [x] Finish slingshot changes
- [ ] Update website so the information is accurate and not as confusing.
- [ ] More config options for enabling and disabling blocks and items
- [ ] More bridges between the different parts
- [ ] More things to add to Cuisine since it is pretty barren
- [ ] Add in all the rest of WeCraft. Arrow Sensor has been the only one for awhile.

**Comment by grim3212** [comment]
Moved elsewhere
